export const LOGIN_ENDPOINT = "/v1/members/login"
export const SIGNUP_ENDPOINT = "/v1/members/signup"
export const QUERY_ENDPOINT = "/v1/members/query"
export const GET_INTENT_ENDPOINT = "/v1/payment/create"
export const CHECK_MEMBERSHIP_ENDPOINT = "/v1/members/check"
